import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;

/**
 * CO3 – EXP_2 | Servlet-Based Student Result Processing
 *
 * Concepts: Servlet architecture, doPost(), request.getParameter(),
 *           validation (missing values & out-of-range marks),
 *           dynamic HTML response via PrintWriter,
 *           local variables for concurrency safety.
 *
 * Deploy in Apache Tomcat webapp and map "/ResultServlet" in web.xml.
 */
public class ResultServlet extends HttpServlet {

    /**
     * doPost() handles the HTML form submission.
     * All student data is stored in LOCAL variables so the servlet
     * remains thread-safe when multiple requests are processed simultaneously.
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        // ── Read form parameters ────────────────────────────────────────────
        String studentName = request.getParameter("studentName");
        String regNumber   = request.getParameter("regNumber");
        String marks1Str   = request.getParameter("marks1");
        String marks2Str   = request.getParameter("marks2");
        String marks3Str   = request.getParameter("marks3");

        // ── Set response type ───────────────────────────────────────────────
        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out = response.getWriter();

        // ── Validation: check for missing/empty fields ──────────────────────
        if (isNullOrEmpty(studentName) || isNullOrEmpty(regNumber) ||
            isNullOrEmpty(marks1Str)   || isNullOrEmpty(marks2Str)  || isNullOrEmpty(marks3Str)) {

            renderError(out, "All fields are required. Please go back and fill in all details.");
            return;
        }

        // ── Validation: parse marks and check range 0–100 ──────────────────
        int m1, m2, m3;
        try {
            m1 = Integer.parseInt(marks1Str.trim());
            m2 = Integer.parseInt(marks2Str.trim());
            m3 = Integer.parseInt(marks3Str.trim());
        } catch (NumberFormatException e) {
            renderError(out, "Marks must be valid integers. Please go back and correct the values.");
            return;
        }

        if (!isValidMark(m1) || !isValidMark(m2) || !isValidMark(m3)) {
            renderError(out, "Marks must be between 0 and 100. Please go back and correct the values.");
            return;
        }

        // ── Calculations (all local variables – thread-safe) ─────────────
        int    total   = m1 + m2 + m3;
        double average = total / 3.0;
        int    highest = Math.max(m1, Math.max(m2, m3));
        int    lowest  = Math.min(m1, Math.min(m2, m3));

        // Pass: average >= 50 AND no subject below 35
        boolean passed = (average >= 50.0) && (m1 >= 35) && (m2 >= 35) && (m3 >= 35);
        String  status = passed ? "PASS" : "FAIL";

        // Grade based on average
        String grade;
        if      (average >= 90) grade = "O  (Outstanding)";
        else if (average >= 80) grade = "A+ (Excellent)";
        else if (average >= 70) grade = "A  (Very Good)";
        else if (average >= 60) grade = "B+ (Good)";
        else if (average >= 50) grade = "B  (Average)";
        else                    grade = "F  (Fail)";

        // ── Render dynamic HTML result ──────────────────────────────────────
        out.println("<!DOCTYPE html>");
        out.println("<html lang='en'>");
        out.println("<head>");
        out.println("  <meta charset='UTF-8'/>");
        out.println("  <meta name='viewport' content='width=device-width, initial-scale=1.0'/>");
        out.println("  <title>Result – " + escapeHtml(studentName) + "</title>");
        out.println("  <link rel='preconnect' href='https://fonts.googleapis.com'/>");
        out.println("  <link href='https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap' rel='stylesheet'/>");
        out.println("  <style>");
        out.println(getResultStyles(passed));
        out.println("  </style>");
        out.println("</head>");
        out.println("<body>");
        out.println("  <div class='page-wrapper'>");
        out.println("    <header class='result-header'>");
        out.println("      <div class='header-icon'>" + (passed ? "🏆" : "📋") + "</div>");
        out.println("      <div>");
        out.println("        <h1>Student Result Card</h1>");
        out.println("        <p class='header-sub'>Generated by ResultServlet via Apache Tomcat</p>");
        out.println("      </div>");
        out.println("    </header>");
        out.println("");
        out.println("    <div class='result-card'>");
        // Student info banner
        out.println("      <div class='student-banner'>");
        out.println("        <div class='avatar'>" + escapeHtml(studentName.trim().substring(0, 1).toUpperCase()) + "</div>");
        out.println("        <div class='student-info'>");
        out.println("          <h2>" + escapeHtml(studentName.trim()) + "</h2>");
        out.println("          <span class='reg-badge'>" + escapeHtml(regNumber.trim().toUpperCase()) + "</span>");
        out.println("        </div>");
        out.println("        <div class='status-pill " + (passed ? "pass" : "fail") + "'>");
        out.println("          " + (passed ? "✅" : "❌") + " " + status);
        out.println("        </div>");
        out.println("      </div>");

        // Marks breakdown
        out.println("      <div class='marks-section'>");
        out.println("        <h3 class='section-label'>📊 Marks Breakdown</h3>");
        out.println("        <div class='marks-grid'>");
        renderMarkBar(out, "Subject 1", m1);
        renderMarkBar(out, "Subject 2", m2);
        renderMarkBar(out, "Subject 3", m3);
        out.println("        </div>");
        out.println("      </div>");

        // Summary stats
        out.println("      <div class='stats-grid'>");
        renderStatCard(out, "🔢 Total",   String.valueOf(total),               "/ 300");
        renderStatCard(out, "📈 Average", String.format("%.2f", average),      "/ 100");
        renderStatCard(out, "🏅 Highest", String.valueOf(highest),             "marks");
        renderStatCard(out, "📉 Lowest",  String.valueOf(lowest),              "marks");
        renderStatCard(out, "🎓 Grade",   grade,                               "");
        out.println("      </div>");

        // Back button
        out.println("      <div class='action-row'>");
        out.println("        <button onclick='history.back()' class='btn-back'>← Back to Form</button>");
        out.println("      </div>");
        out.println("    </div>");
        out.println("  </div>");
        out.println("</body>");
        out.println("</html>");
    }

    // ── Utility Methods ──────────────────────────────────────────────────────

    private boolean isNullOrEmpty(String s) {
        return s == null || s.trim().isEmpty();
    }

    private boolean isValidMark(int m) {
        return m >= 0 && m <= 100;
    }

    private String escapeHtml(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\"", "&quot;").replace("'", "&#39;");
    }

    private void renderMarkBar(PrintWriter out, String subject, int mark) {
        String barClass = mark >= 50 ? "bar-pass" : "bar-fail";
        out.println("          <div class='mark-row'>");
        out.println("            <span class='subject-label'>" + subject + "</span>");
        out.println("            <div class='bar-track'>");
        out.println("              <div class='bar-fill " + barClass + "' style='width:" + mark + "%'></div>");
        out.println("            </div>");
        out.println("            <span class='mark-val'>" + mark + "</span>");
        out.println("          </div>");
    }

    private void renderStatCard(PrintWriter out, String label, String value, String suffix) {
        out.println("        <div class='stat-card'>");
        out.println("          <span class='stat-label'>" + label + "</span>");
        out.println("          <span class='stat-value'>" + value + "</span>");
        if (!suffix.isEmpty()) {
            out.println("          <span class='stat-suffix'>" + suffix + "</span>");
        }
        out.println("        </div>");
    }

    private void renderError(PrintWriter out, String message) {
        out.println("<!DOCTYPE html><html lang='en'><head>");
        out.println("<meta charset='UTF-8'/><meta name='viewport' content='width=device-width,initial-scale=1.0'/>");
        out.println("<title>Validation Error</title>");
        out.println("<link href='https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap' rel='stylesheet'/>");
        out.println("<style>*{box-sizing:border-box;margin:0;padding:0}");
        out.println("body{font-family:'Inter',sans-serif;background:#0f1117;color:#e8eaf6;");
        out.println("  min-height:100vh;display:flex;align-items:center;justify-content:center;}");
        out.println(".err-box{background:#1a1d27;border:1px solid rgba(248,113,113,0.3);border-radius:16px;");
        out.println("  padding:40px;max-width:480px;text-align:center;}");
        out.println(".err-icon{font-size:3rem;margin-bottom:16px;}");
        out.println("h2{font-size:1.4rem;font-weight:700;color:#f87171;margin-bottom:12px;}");
        out.println("p{color:#9094b5;font-size:0.9rem;line-height:1.6;margin-bottom:24px;}");
        out.println(".btn{background:linear-gradient(135deg,#a78bfa,#4f8ef7);color:#fff;border:none;");
        out.println("  border-radius:10px;padding:12px 26px;font-size:0.9rem;font-weight:600;cursor:pointer;}");
        out.println(".btn:hover{opacity:0.85;}</style></head><body>");
        out.println("<div class='err-box'><div class='err-icon'>⚠️</div>");
        out.println("<h2>Validation Error</h2>");
        out.println("<p>" + escapeHtml(message) + "</p>");
        out.println("<button class='btn' onclick='history.back()'>← Go Back</button>");
        out.println("</div></body></html>");
    }

    private String getResultStyles(boolean passed) {
        return "*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n" +
               ":root {\n" +
               "  --bg-base: #0f1117; --bg-card: #1a1d27;\n" +
               "  --accent-blue: #4f8ef7; --accent-purple: #a78bfa;\n" +
               "  --accent-green: #34d399; --accent-red: #f87171;\n" +
               "  --accent-amber: #fbbf24;\n" +
               "  --text-primary: #e8eaf6; --text-secondary: #9094b5;\n" +
               "  --border: rgba(255,255,255,0.08);\n" +
               "}\n" +
               "body { font-family: 'Inter', sans-serif; background: var(--bg-base);\n" +
               "  color: var(--text-primary); min-height: 100vh;\n" +
               "  background-image: radial-gradient(ellipse 80% 50% at 50% 0%,\n" +
               "    " + (passed ? "rgba(52,211,153,0.10)" : "rgba(248,113,113,0.10)") + " 0%, transparent 60%); }\n" +
               ".page-wrapper { max-width: 800px; margin: 0 auto; padding: 24px 20px 60px; }\n" +
               ".result-header { display: flex; align-items: center; gap: 20px;\n" +
               "  padding: 28px 36px; margin-bottom: 28px;\n" +
               "  background: linear-gradient(135deg,\n" +
               "    " + (passed ? "rgba(52,211,153,0.15), rgba(79,142,247,0.10)" : "rgba(248,113,113,0.12), rgba(251,191,36,0.08)") + ");\n" +
               "  border: 1px solid var(--border); border-radius: 16px; }\n" +
               ".header-icon { font-size: 3rem; }\n" +
               ".result-header h1 { font-size: 1.8rem; font-weight: 800;\n" +
               "  background: linear-gradient(135deg, " + (passed ? "var(--accent-green), var(--accent-blue)" : "var(--accent-red), var(--accent-amber)") + ");\n" +
               "  -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }\n" +
               ".header-sub { color: var(--text-secondary); font-size: 0.85rem; margin-top: 4px; }\n" +
               ".result-card { background: #1a1d27; border: 1px solid var(--border);\n" +
               "  border-radius: 16px; overflow: hidden; box-shadow: 0 8px 32px rgba(0,0,0,0.45); }\n" +
               ".student-banner { display: flex; align-items: center; gap: 18px; flex-wrap: wrap;\n" +
               "  background: linear-gradient(135deg, rgba(79,142,247,0.15), rgba(167,139,250,0.10));\n" +
               "  padding: 24px 28px; border-bottom: 1px solid var(--border); }\n" +
               ".avatar { width: 60px; height: 60px; border-radius: 50%;\n" +
               "  background: linear-gradient(135deg, var(--accent-blue), var(--accent-purple));\n" +
               "  display: flex; align-items: center; justify-content: center;\n" +
               "  font-size: 1.6rem; font-weight: 800; color: #fff; flex-shrink: 0;\n" +
               "  box-shadow: 0 4px 16px rgba(79,142,247,0.4); }\n" +
               ".student-info { flex: 1; }\n" +
               ".student-info h2 { font-size: 1.3rem; font-weight: 700; }\n" +
               ".reg-badge { display: inline-block; margin-top: 6px; background: rgba(79,142,247,0.15);\n" +
               "  color: var(--accent-blue); font-size: 0.75rem; font-weight: 600;\n" +
               "  padding: 4px 12px; border-radius: 30px; border: 1px solid rgba(79,142,247,0.3); }\n" +
               ".status-pill { font-size: 0.9rem; font-weight: 700; padding: 8px 20px;\n" +
               "  border-radius: 30px; border: 1px solid; }\n" +
               ".status-pill.pass { background: rgba(52,211,153,0.15); color: var(--accent-green); border-color: rgba(52,211,153,0.3); }\n" +
               ".status-pill.fail { background: rgba(248,113,113,0.15); color: var(--accent-red);   border-color: rgba(248,113,113,0.3); }\n" +
               ".marks-section { padding: 24px 28px; border-bottom: 1px solid var(--border); }\n" +
               ".section-label { font-size: 0.88rem; font-weight: 700; color: var(--accent-amber);\n" +
               "  text-transform: uppercase; letter-spacing: 0.06em; margin-bottom: 16px; }\n" +
               ".marks-grid { display: flex; flex-direction: column; gap: 14px; }\n" +
               ".mark-row { display: flex; align-items: center; gap: 12px; }\n" +
               ".subject-label { width: 75px; font-size: 0.82rem; font-weight: 600; color: var(--text-secondary); flex-shrink: 0; }\n" +
               ".bar-track { flex: 1; height: 10px; background: rgba(255,255,255,0.06);\n" +
               "  border-radius: 30px; overflow: hidden; }\n" +
               ".bar-fill { height: 100%; border-radius: 30px; transition: width 0.6s ease; }\n" +
               ".bar-pass { background: linear-gradient(90deg, var(--accent-green), var(--accent-blue)); }\n" +
               ".bar-fail { background: linear-gradient(90deg, var(--accent-red), #fb923c); }\n" +
               ".mark-val { width: 30px; text-align: right; font-size: 0.9rem; font-weight: 700; }\n" +
               ".stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));\n" +
               "  gap: 1px; background: var(--border); }\n" +
               ".stat-card { background: #1a1d27; padding: 20px; display: flex;\n" +
               "  flex-direction: column; gap: 4px; }\n" +
               ".stat-label { font-size: 0.8rem; font-weight: 600; color: var(--text-secondary); }\n" +
               ".stat-value { font-size: 1.4rem; font-weight: 800; color: var(--text-primary); }\n" +
               ".stat-suffix { font-size: 0.75rem; color: var(--text-secondary); }\n" +
               ".action-row { padding: 20px 28px; border-top: 1px solid var(--border); }\n" +
               ".btn-back { background: linear-gradient(135deg, var(--accent-purple), var(--accent-blue));\n" +
               "  color: #fff; border: none; border-radius: 10px; padding: 12px 26px;\n" +
               "  font-family: 'Inter', sans-serif; font-size: 0.9rem; font-weight: 600;\n" +
               "  cursor: pointer; transition: opacity 0.2s ease; }\n" +
               ".btn-back:hover { opacity: 0.85; }\n";
    }
}
